// <auto-generated />
namespace Ideas.WebApi.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class init2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103070814367_init2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
